stuff=list()
stuff.append(8)
stuff.append(23)
stuff.append(2.0)
stuff.append(3)
stuff.append(4)
print(stuff)
print(3 in stuff)
print(2 in stuff)
print(6 not in stuff)
print('book' in stuff)
print(7 in stuff)
stuff.sort()
print(stuff)
stuff.insert(2,'book')
print(stuff)
stuff[2]=17
stuff.sort()
print(stuff)
print('length = ',len(stuff))
print('min = ',min(stuff))
print('max = ',max(stuff))
print('sum = ',sum(stuff))
print('Average = ', sum(stuff)/len(stuff))
